set search_path = bullish_banana, extensions, public;

-- Official Hantec Trader selector and support pages reviewed 2026-09-28.
-- Program rows remain in_review while checkout/legal conditions are reconciled.
insert into bullish_banana.firms (name, slug, description, website_url, status, published_at)
values ('Hantec Trader', 'hantec-trader', 'A simulated multi-asset trading challenge and instant funding service operated by Hantec Trader Limited.', 'https://htrader.hmarkets.com/', 'published', now())
on conflict (slug) do update
set name=excluded.name, description=excluded.description, website_url=excluded.website_url,
    status='published', published_at=coalesce(bullish_banana.firms.published_at,now()),
    archived_at=null, updated_at=now();

insert into bullish_banana.firm_markets (firm_id, market_type)
select id,'forex' from bullish_banana.firms where slug='hantec-trader'
on conflict (firm_id,market_type) do nothing;

insert into bullish_banana.firm_profiles (firm_id,country_code,legal_entity_name,supported_assets,profile_details)
select id,'MU','Hantec Trader Limited',array['Forex','Indices','Commodities','Precious metals','Cryptocurrencies']::text[],
  '{"legal_entity":"Hantec Trader Limited (Company No. C191400), incorporated in Mauritius; registered office Suite 201, The Catalyst, Silicon Avenue, 40 Cybercity, Ebene, Mauritius.","service_model":"Challenges and Hantec Trader accounts are simulated/demo accounts with virtual funds. Hantec Trader states it is not a broker, does not accept deposits and does not conduct regulated activities.","group_relationship":"Hantec Trader Limited and Hantec Markets Limited are distinct legal entities. Terms say simulated platform hosting is on Hantec Markets Limited trading servers. HM Provider Limited provides transaction support services.","platform":"Official site names Platform 5; support articles refer to MT5 accounts. Verify exact platform naming/account availability at checkout before publication.","forex_leverage":"50:1 by asset class; precious metals 10:1, indices and commodities 15:1, crypto 1:1.","current_forex_offers":["Express","Enhanced","EnhancedX","Endurance","Instant Funding","Instant Lite","Instant24"],"firm_restrictions":"Official Help Center lists Afghanistan, Australia, Belgium, Congo (Brazzaville), Congo (Kinshasa), Czech Republic, Egypt, Germany, Haiti, Iran, Israel, Jordan, Kosovo, Laos, Libya, Malaysia, Myanmar, North Korea, Pakistan, Puerto Rico, Qatar, Romania, Russia, Serbia, Somalia, South Sudan, Taiwan, Thailand, United States, Uzbekistan, Vietnam, and Yemen. The website also excludes US residents/citizens.","instant_program_restrictions":"The homepage disclaimer separately says Instant programs are unavailable to residents of the United Kingdom, Mauritius, Hong Kong, and Singapore. Keep this restriction attached to Instant products, not the entire firm.","account_allocation":"Maximum combined allocation USD 400,000; one Instant account at a time; up to three Instant24 accounts, which do not count toward the Instant-account limit.","age_requirement":"Help Center says customers must be over 18.","content_note":"Selector sizes and base USD fees were captured without applying a promo code. Coupon banners were visible; promotional checkout pricing can differ."}'::jsonb
from bullish_banana.firms where slug='hantec-trader'
on conflict (firm_id) do update
set country_code=excluded.country_code, legal_entity_name=excluded.legal_entity_name,
    supported_assets=excluded.supported_assets,
    profile_details=bullish_banana.firm_profiles.profile_details || excluded.profile_details,
    updated_at=now();

insert into bullish_banana.programs (
  firm_id,name,slug,description,program_type,market_type,status,currency,account_sizes,
  max_leverage,profit_split_percent,payout_frequency,minimum_trading_days,
  news_allowed,weekend_holding_allowed,commercial_details,published_at,archived_at
)
select f.id,x.name,x.slug,x.description,x.program_type,'forex','in_review','USD',x.sizes::jsonb,
       50::numeric,x.split,x.payout,x.days,x.news,x.weekends,x.details::jsonb,null,null
from bullish_banana.firms f
join (values
 ('Express','express','Single-stage Forex evaluation with a 10% target, no minimum or maximum duration, and a 6% trailing maximum loss.','evaluation','[2000,5000,10000,25000,50000,100000,200000]',80::numeric,'Every 14 days; 7 days with add-on',null,true,true,'{"account_size_prices":[{"account_size":2000,"fee":39,"currency":"USD"},{"account_size":5000,"fee":59,"currency":"USD"},{"account_size":10000,"fee":99,"currency":"USD"},{"account_size":25000,"fee":199,"currency":"USD"},{"account_size":50000,"fee":319,"currency":"USD"},{"account_size":100000,"fee":529,"currency":"USD"},{"account_size":200000,"fee":999,"currency":"USD"}],"challenge_rules":"10% target. Daily limit 5% based at 00:00 server time on the higher end-of-day balance or equity. Max total loss 6% trails closed balance and locks at initial balance after a 6% balance gain. No minimum or maximum trading period. Weekend holding allowed. News unrestricted during challenge; funded news trading restricted 3 minutes before/after red-folder events by default.","funded_rules":"Default reward share 80%; first reward request 14 days after first trade; minimum request USD 20. At first withdrawal max loss locks to initial balance. Funded open exposure max 3% of starting balance. Inactivity breach after 30 days without a trade.","add_ons":"Optional 95% split, weekly payout, first payout on demand, 8% target via -2% target add-on, max loss +2% (8%), and funded news trading. Verify exact checkout prices and combinations.","eligibility_note":"All firm-restricted countries apply. Current site also excludes US residents/citizens.","pricing_capture":"Official USD selector prices captured 2026-09-28 without entering coupon codes; coupon banner was visible.","source_note":"Official Express selector, Express rules, terms, leverage and eligibility sources reviewed 2026-09-28."}'),
 ('Enhanced','enhanced','Two-stage evaluation with 10% and 5% targets and three 0.5%-profitable days required in each stage.','evaluation','[5000,10000,25000,50000,100000,200000]',80::numeric,'Every 14 days; 7 days with add-on',null,true,true,'{"account_size_prices":[{"account_size":5000,"fee":59,"currency":"USD"},{"account_size":10000,"fee":99,"currency":"USD"},{"account_size":25000,"fee":219,"currency":"USD"},{"account_size":50000,"fee":359,"currency":"USD"},{"account_size":100000,"fee":599,"currency":"USD"},{"account_size":200000,"fee":1169,"currency":"USD"}],"challenge_rules":"Targets 10% then 5%. Daily limit 5% based on the higher balance/equity at 00:00 server time. Maximum total loss 10% static. Each stage requires 3 profitable days, with at least 0.5% starting-balance profit per day. No maximum duration. Weekend holding allowed. News unrestricted during challenge.","funded_rules":"Default split 80%; first reward 14 days after first trade; minimum request USD 20; minimum 3 profitable days at 0.5% per day per payout cycle. Maximum funded open exposure 3% of starting balance. Funded red-folder news restriction is ±3 minutes by default. At first withdrawal, max loss locks at starting balance.","add_ons":"Optional 95% split, weekly payout, first payout on demand, news trading in funded stage and no minimum profitable days. Verify exact checkout combinations.","eligibility_note":"All firm-restricted countries apply. Current site also excludes US residents/citizens.","pricing_capture":"Official USD selector prices captured 2026-09-28 without entering coupon codes; coupon banner was visible.","source_note":"Official Enhanced selector and rules, support FAQ, terms, leverage and eligibility sources reviewed 2026-09-28."}'),
 ('EnhancedX','enhancedx','Two-stage evaluation with 8% and 4% targets and a 35% best-day consistency limit.','evaluation','[5000,10000,25000,50000,100000,200000]',80::numeric,'Every 14 days; 7 days with add-on',null,true,true,'{"account_size_prices":[{"account_size":5000,"fee":59,"currency":"USD"},{"account_size":10000,"fee":99,"currency":"USD"},{"account_size":25000,"fee":219,"currency":"USD"},{"account_size":50000,"fee":359,"currency":"USD"},{"account_size":100000,"fee":599,"currency":"USD"},{"account_size":200000,"fee":1169,"currency":"USD"}],"challenge_rules":"Current official selector: targets 8% then 4%; daily loss 4% based on higher end-of-day balance/equity; max total loss 8% static; 35% consistency based on best day equity vs total profit; no minimum profitable days and no maximum duration; weekend holding allowed; no challenge-phase news restriction.","funded_rules":"Default 80% share; first reward after 14 days; minimum withdrawal requires 2% profit on starting balance; funded news restricted ±3 minutes by default; funded open risk capped at 3%. English Help Center article reviewed 2026-09-28.","source_conflict":"EnhancedX help article add-on text describes a +2% max-loss add-on from 6% to 8%, inconsistent with its own standard 8% selector value. Confirm current contract/add-on semantics before publishing.","add_ons":"95% split, weekly payout, remove consistency during challenge, max-loss adjustment, first payout on demand, and funded news trading are described. Verify actual price and compatibility at checkout.","eligibility_note":"All firm-restricted countries apply; current site excludes US residents/citizens.","pricing_capture":"Official USD selector prices captured 2026-09-28 without entering coupon codes; coupon banner was visible.","source_note":"Official English EnhancedX support rules and live selector, Terms, leverage and eligibility sources reviewed 2026-09-28."}'),
 ('Endurance','endurance','Three-stage Forex evaluation with a 6% target in each stage and fixed 8% maximum loss.','evaluation','[5000,10000,25000,50000,100000,200000]',80::numeric,'Every 14 days; 7 days with add-on',3,true,true,'{"account_size_prices":[{"account_size":5000,"fee":29,"currency":"USD"},{"account_size":10000,"fee":59,"currency":"USD"},{"account_size":25000,"fee":109,"currency":"USD"},{"account_size":50000,"fee":189,"currency":"USD"},{"account_size":100000,"fee":299,"currency":"USD"},{"account_size":200000,"fee":499,"currency":"USD"}],"challenge_rules":"Targets 6% / 6% / 6%. Daily loss 4%, calculated at 00:00 server time against the higher of end-of-day balance/equity. Max total loss 8% static. Each stage requires 3 trading days. No max duration. Weekend holding allowed. News has no restrictions during challenge.","funded_rules":"Default 80% reward share and first request 14 days after first trade; min withdrawal USD 20. Funded news trading restricted ±3 minutes by default, max open risk 3% and inactivity limit 30 days. Static max-loss floor remains 8% under start balance after withdrawal.","add_ons":"95% split, weekly payout, first payout on demand, funded news trading, and no minimum trading days are offered. Verify exact checkout combinations.","eligibility_note":"All firm-restricted countries apply; current site excludes US residents/citizens.","pricing_capture":"Official USD selector prices captured 2026-09-28 without entering coupon codes; coupon banner was visible.","source_note":"Official Endurance selector and support rules, terms, leverage and eligibility sources reviewed 2026-09-28."}'),
 ('Instant Funding','instant-funding','Direct-funded simulated Forex account with no evaluation phase, 6% daily loss and 6% trailing maximum loss.','instant_funding','[1000,2000,5000,10000,25000,50000]',80::numeric,'Every 14 days; 7 days with add-on',null,false,false,'{"account_size_prices":[{"account_size":1000,"fee":43,"currency":"USD"},{"account_size":2000,"fee":86,"currency":"USD"},{"account_size":5000,"fee":214,"currency":"USD"},{"account_size":10000,"fee":428,"currency":"USD"},{"account_size":25000,"fee":1069,"currency":"USD"},{"account_size":50000,"fee":2139,"currency":"USD"}],"challenge_rules":"No evaluation or target. Daily loss 6%, recalculated at server midnight from higher prior end-of-day balance/equity. Max loss 6% trailing balance and locks at starting balance after 6% growth. Maximum open risk 3% of start balance. No minimum or maximum trading period. News and weekend trading are restricted by default; help page says ±3 minutes around red-folder events and close trades by Friday 23:45 GMT+3.","funded_rules":"Default 80% split, 14-day payout cycle, USD 20 minimum request. First withdrawal locks max-loss floor to starting balance. EAs prohibited for Instant accounts. 30-day inactivity hard breach.","add_ons":"Optional 95% split, weekly payout, +1% max loss, and weekend/news trading. Verify exact checkout combinations.","eligibility_note":"Instant programs unavailable to residents of UK, Mauritius, Hong Kong and Singapore; all firm-restricted jurisdictions apply, including US. Check current checkout country list.","pricing_capture":"Official USD selector prices captured 2026-09-28 without entering coupon codes; coupon banner was visible.","source_note":"Official current selector and homepage, Instant Funding help article, terms, leverage and eligibility sources reviewed 2026-09-28. Help article page was available in Portuguese; verify English wording before publication."}'),
 ('Instant Lite','instant-lite','Direct-funded account with 3% daily loss, 5% trailing maximum loss, a consistency rule and mandatory 3% safety buffer.','instant_funding','[1000,2000,5000,10000,25000,50000,100000]',80::numeric,'Every 14 days; 7 days with add-on',null,false,false,'{"account_size_prices":[{"account_size":1000,"fee":19,"currency":"USD"},{"account_size":2000,"fee":39,"currency":"USD"},{"account_size":5000,"fee":79,"currency":"USD"},{"account_size":10000,"fee":129,"currency":"USD"},{"account_size":25000,"fee":239,"currency":"USD"},{"account_size":50000,"fee":369,"currency":"USD"},{"account_size":100000,"fee":699,"currency":"USD"}],"challenge_rules":"No evaluation or target. Daily limit 3% based on higher end-of-day balance/equity; max loss 5% trails closed balance and locks at initial balance after reaching 5% profit. 20% best-day consistency; five payout-cycle profitable days of at least 0.5% each; 1% maximum open risk; 3% of starting balance is a non-withdrawable safety buffer. No maximum duration; weekend holding and red-folder news are disallowed by default; EAs prohibited.","funded_rules":"Default 80% reward share; first payout 14 days after first trade; minimum request USD 20. The 3% safety buffer applies and is included in consistency calculation. 30-day inactivity limit.","add_ons":"Optional 95% split, weekly payout, consistency cap +5 points, max loss +1%, and weekend/news access. Verify exact checkout combinations.","eligibility_note":"Instant programs unavailable to residents of UK, Mauritius, Hong Kong and Singapore; all firm-restricted jurisdictions apply, including US.","pricing_capture":"Official USD selector prices captured 2026-09-28 without entering coupon codes; coupon banner was visible.","source_note":"Official current selector and Instant Lite support rules, terms, leverage and eligibility sources reviewed 2026-09-28."}'),
 ('Instant24','instant24','Time-limited direct-funded account requiring all trading activity within 24 hours of the first trade.','instant_funding','[2000,5000,10000,25000,50000,100000]',80::numeric,'One-time payout after 24-hour window',null,true,false,'{"account_size_prices":[{"account_size":2000,"fee":13,"currency":"USD"},{"account_size":5000,"fee":17,"currency":"USD"},{"account_size":10000,"fee":38,"currency":"USD"},{"account_size":25000,"fee":89,"currency":"USD"},{"account_size":50000,"fee":190,"currency":"USD"},{"account_size":100000,"fee":299,"currency":"USD"}],"challenge_rules":"No evaluation or target. Total activity must finish within 24 hours from first trade. Daily loss 2% based on the higher previous day end balance/equity. Max loss 3% trailing closed balance. Open risk cap 1%; at most one open position; 3% profit is required to request a reward; single trade cannot exceed 15% of total profits. News trading is allowed. EAs are prohibited.","funded_rules":"Default 80% reward share; payout after 24 hours if rules are met and the full withdrawal is requested. No scaling. All open positions close before Friday market close; crypto can be traded after close on weekends. 30-day inactivity limit.","add_ons":"Optional 95% split and an additional 12 hours (36-hour window). Verify checkout options.","eligibility_note":"Instant programs unavailable to residents of UK, Mauritius, Hong Kong and Singapore; all firm-restricted jurisdictions apply, including US.","pricing_capture":"Official USD selector prices captured 2026-09-28 without entering coupon codes; coupon banner was visible.","source_note":"Official current selector and Instant24 support rules, terms, leverage and eligibility sources reviewed 2026-09-28."}')
) as x(name,slug,description,program_type,sizes,split,payout,days,news,weekends,details) on true
where f.slug='hantec-trader'
on conflict (firm_id,slug) do update
set name=excluded.name,description=excluded.description,program_type=excluded.program_type,
    market_type=excluded.market_type,status='in_review',currency=excluded.currency,
    account_sizes=excluded.account_sizes,max_leverage=excluded.max_leverage,
    profit_split_percent=excluded.profit_split_percent,payout_frequency=excluded.payout_frequency,
    minimum_trading_days=excluded.minimum_trading_days,news_allowed=excluded.news_allowed,
    weekend_holding_allowed=excluded.weekend_holding_allowed,commercial_details=excluded.commercial_details,
    published_at=null,archived_at=null,updated_at=now();

insert into bullish_banana.program_phases (
  program_id,phase_number,name,profit_target_percent,daily_drawdown_percent,
  maximum_drawdown_percent,drawdown_type,time_limit_days,minimum_trading_days,raw_rules
)
select p.id,x.phase_number,x.name,x.target,x.daily,x.maximum,x.kind,x.days,x.minimum,x.rules::jsonb
from bullish_banana.programs p
join bullish_banana.firms f on f.id=p.firm_id
join (values
 ('express',1,'Stage 1',10::numeric,5::numeric,6::numeric,'trailing',null::integer,null::integer,'{"daily_basis":"At server midnight, higher of end-of-day balance or equity."}'),
 ('enhanced',1,'Stage 1',10::numeric,5::numeric,10::numeric,'static',null::integer,3::integer,'{"minimum_profitable_days":3,"minimum_profit_per_day_percent":0.5,"daily_basis":"At server midnight, higher of end-of-day balance or equity."}'),
 ('enhanced',2,'Stage 2',5::numeric,5::numeric,10::numeric,'static',null::integer,3::integer,'{"minimum_profitable_days":3,"minimum_profit_per_day_percent":0.5,"daily_basis":"At server midnight, higher of end-of-day balance or equity."}'),
 ('enhancedx',1,'Stage 1',8::numeric,4::numeric,8::numeric,'static',null::integer,null::integer,'{"consistency_percent":35,"consistency_basis":"Best trading day end-of-day equity profit divided by total profits.","daily_basis":"At server midnight, higher of end-of-day balance or equity.","source_language":"Official English Help Center article reviewed 2026-09-28."}'),
 ('enhancedx',2,'Stage 2',4::numeric,4::numeric,8::numeric,'static',null::integer,null::integer,'{"consistency_percent":35,"consistency_basis":"Best trading day end-of-day equity profit divided by total profits.","daily_basis":"At server midnight, higher of end-of-day balance or equity.","source_language":"Official English Help Center article reviewed 2026-09-28."}'),
 ('endurance',1,'Stage 1',6::numeric,4::numeric,8::numeric,'static',null::integer,3::integer,'{"daily_basis":"At server midnight, higher of end-of-day balance or equity."}'),
 ('endurance',2,'Stage 2',6::numeric,4::numeric,8::numeric,'static',null::integer,3::integer,'{"daily_basis":"At server midnight, higher of end-of-day balance or equity."}'),
 ('endurance',3,'Stage 3',6::numeric,4::numeric,8::numeric,'static',null::integer,3::integer,'{"daily_basis":"At server midnight, higher of end-of-day balance or equity."}')
) as x(program_slug,phase_number,name,target,daily,maximum,kind,days,minimum,rules) on x.program_slug=p.slug
where f.slug='hantec-trader'
on conflict (program_id,phase_number) do update
set name=excluded.name,profit_target_percent=excluded.profit_target_percent,
    daily_drawdown_percent=excluded.daily_drawdown_percent,
    maximum_drawdown_percent=excluded.maximum_drawdown_percent,drawdown_type=excluded.drawdown_type,
    time_limit_days=excluded.time_limit_days,minimum_trading_days=excluded.minimum_trading_days,
    raw_rules=excluded.raw_rules,updated_at=now();

insert into bullish_banana.platforms (name,slug) values ('Platform 5','platform-5')
on conflict (slug) do update set name=excluded.name;
insert into bullish_banana.program_platforms (program_id,platform_id)
select p.id,pl.id from bullish_banana.programs p
join bullish_banana.firms f on f.id=p.firm_id and f.slug='hantec-trader'
join bullish_banana.platforms pl on pl.slug='platform-5'
on conflict do nothing;

insert into bullish_banana.restrictions (firm_id,country_code,restriction_type,note)
select f.id,x.code,'restricted','Hantec Trader official restricted-jurisdiction FAQ, captured 2026-09-28. Instant products also have additional region exclusions stored in firm profile details.'
from bullish_banana.firms f
cross join (values ('AF'),('AU'),('BE'),('CG'),('CD'),('CZ'),('EG'),('DE'),('HT'),('IR'),('IL'),('JO'),('XK'),('LA'),('LY'),('MY'),('MM'),('KP'),('PK'),('PR'),('QA'),('RO'),('RU'),('RS'),('SO'),('SS'),('TW'),('TH'),('US'),('UZ'),('VN'),('YE')) as x(code)
where f.slug='hantec-trader'
on conflict (firm_id,country_code) do update set restriction_type=excluded.restriction_type,note=excluded.note,updated_at=now();

insert into bullish_banana.sources (firm_id,source_url,source_label,notes)
select f.id,x.url,x.label,x.notes from bullish_banana.firms f join (values
 ('https://htrader.hmarkets.com/','Official Hantec Trader homepage and live selector','Selector size/price matrices and product cards captured 2026-09-28; page contains current promo banners but no code was applied.'),
 ('https://htrader.hmarkets.com/terms-conditions/','Hantec Trader Terms and Conditions','Current legal operator and simulated account, server and allocation terms.'),
 ('https://help.htrader.hmarkets.com/en/support/solutions/articles/158000444228-%E0%B8%A1%E0%B8%B5%E0%B8%9B%E0%B8%A3%E0%B8%B0%E0%B9%80%E0%B8%97%E0%B8%A8%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B8%96%E0%B8%B9%E0%B8%81%E0%B8%88%E0%B8%B3%E0%B8%81%E0%B8%B1%E0%B8%94%E0%B8%AA%E0%B8%B3%E0%B8%AB%E0%B8%A3%E0%B8%B1%E0%B8%9A-hantec-trader-%E0%B8%AB%E0%B8%A3%E0%B8%B7%E0%B8%AD%E0%B9%84%E0%B8%A1%E0%B9%88-','Restricted countries FAQ','Firm-wide restricted jurisdictions. Homepage separately excludes US residents/citizens and lists Instant-only country exclusions.'),
 ('https://help.htrader.hmarkets.com/es-LA/support/solutions/articles/158000444269--cu%C3%A1l-es-el-apalancamiento-para-cada-challenge-','Leverage by asset class FAQ','Forex leverage is 50:1; other asset classes differ.'),
 ('https://htrader.hmarkets.com/platforms/','Platform 5','Official platform details; confirm account-specific platform availability at checkout.'),
 ('https://htrader.hmarkets.com/trading/product-specifications/','Product specifications','Forex instruments, contract specifications, spreads and commissions.'),
 ('https://help.htrader.hmarkets.com/en/support/solutions','Official Help Center account and trading rules index','Current seven-program lineup, trading rules, payouts, platform, restrictions and account FAQs.'),
 ('https://help.htrader.hmarkets.com/en/support/solutions','Expert Advisor and trading-rules index','Official support lists account-specific EA conditions; Instant products prohibit EAs.')
) as x(url,label,notes) on true where f.slug='hantec-trader'
and not exists(select 1 from bullish_banana.sources s where s.firm_id=f.id and s.source_url=x.url);

insert into bullish_banana.sources (program_id,source_url,source_label,notes)
select p.id,x.url,x.label,x.notes from bullish_banana.programs p
join bullish_banana.firms f on f.id=p.firm_id
join (values
 ('express','https://htrader.hmarkets.com/','Express live selector','All seven USD size/base fee pairs captured 2026-09-28, without a coupon.'),
 ('express','https://help.htrader.hmarkets.com/en/support/solutions/articles/158000445797-express-1-step-','Express official rules','Evaluation, funded, drawdown, payout and add-on rules.'),
 ('enhanced','https://htrader.hmarkets.com/','Enhanced live selector','All six USD size/base fee pairs captured 2026-09-28, without a coupon.'),
 ('enhanced','https://help.htrader.hmarkets.com/en/support/solutions/articles/158000445798-enhanced','Enhanced official rules','Targets, drawdown, min profitable days, payout and add-on rules.'),
 ('enhancedx','https://htrader.hmarkets.com/','EnhancedX live selector','All six USD size/base fee pairs captured 2026-09-28, without a coupon.'),
 ('enhancedx','https://help.htrader.hmarkets.com/en/support/solutions/articles/158000445799-enhancedx-2-step-consistency-','EnhancedX official rules','Current support article in Portuguese; 35% consistency and add-on wording conflicts with selector; retain under review.'),
 ('endurance','https://htrader.hmarkets.com/','Endurance live selector','All six USD size/base fee pairs captured 2026-09-28, without a coupon.'),
 ('endurance','https://help.htrader.hmarkets.com/en/support/solutions/articles/158000445800-endurance-3-step-challenge-','Endurance official rules','Three-stage targets, loss limits, minimum days, payouts and funded terms.'),
 ('instant-funding','https://htrader.hmarkets.com/','Instant Funding live selector','All six USD size/base fee pairs captured 2026-09-28, without a coupon.'),
 ('instant-funding','https://help.htrader.hmarkets.com/pt-BR/support/solutions/articles/158000445801-instant-funding','Instant Funding support rules','Current official article page available in Portuguese; verify English/legal wording and term dates before publication.'),
 ('instant-lite','https://htrader.hmarkets.com/','Instant Lite live selector','All seven USD size/base fee pairs captured 2026-09-28, without a coupon.'),
 ('instant-lite','https://help.htrader.hmarkets.com/en/support/solutions/articles/158000445802-instant-lite','Instant Lite official rules','Current direct-funded rules, safety buffer and consistency/payout conditions.'),
 ('instant24','https://htrader.hmarkets.com/','Instant24 live selector','All six USD size/base fee pairs captured 2026-09-28, without a coupon.'),
 ('instant24','https://help.htrader.hmarkets.com/en/support/solutions/articles/158000445803-instant24','Instant24 official rules','24-hour window, loss limits, open-trade, consistency and payout rules.')
) as x(program_slug,url,label,notes) on x.program_slug=p.slug
where f.slug='hantec-trader'
and not exists(select 1 from bullish_banana.sources s where s.program_id=p.id and s.source_url=x.url);

insert into bullish_banana.data_verifications (firm_id,verified_at,notes)
select id,now(),'Hantec Trader official site, current seven-product USD selectors, Terms, restricted-country FAQ, leverage, platform and product-specification disclosures reviewed 2026-09-28.'
from bullish_banana.firms f where slug='hantec-trader'
and not exists(select 1 from bullish_banana.data_verifications v where v.firm_id=f.id);

insert into bullish_banana.data_verifications (program_id,verified_at,notes)
select p.id,now(),'Current official selector USD sizes/prices and model-specific support rules reviewed 2026-09-28. In review pending verification of account-specific terms/add-ons, live platform compatibility and remaining rule/locale conflicts.'
from bullish_banana.programs p join bullish_banana.firms f on f.id=p.firm_id
where f.slug='hantec-trader'
and not exists(select 1 from bullish_banana.data_verifications v where v.program_id=p.id);

