begin;
set search_path = bullish_banana, extensions, public;

with offers(firm_slug, program_slug, label, source_url, source_title, disclosure, verification) as (
  values
    ('fundingpips','2-step-pro-model','FundingPips 2-Step Pro platform scope','https://help.fundingpips.com/hc/en-us/articles/43468639481105-Account-Workspace','FundingPips account workspace and platform selection — 2026-10-01',
      'FundingPips lists MetaTrader 5, cTrader, and Match-Trader as firm-level platforms. Its official onboarding describes choosing a model, account size, and platform, but the reviewed public material does not specify the exact platform choices enabled for this offer. Confirm the platform in the live offer selector before purchase.',
      'Reviewed FundingPips official account-workspace and onboarding pages on 2026-10-01. They establish the three firm-level platforms and a model/platform selection flow, but do not publish a model-specific platform mapping for 2-Step Pro.'),
    ('fundingpips','2-step-flex','FundingPips 2-Step Flex platform scope','https://help.fundingpips.com/hc/en-us/articles/43468639481105-Account-Workspace','FundingPips account workspace and platform selection — 2026-10-01',
      'FundingPips lists MetaTrader 5, cTrader, and Match-Trader as firm-level platforms. Its official onboarding describes choosing a model, account size, and platform, but the reviewed public material does not specify the exact platform choices enabled for this offer. Confirm the platform in the live offer selector before purchase.',
      'Reviewed FundingPips official account-workspace and onboarding pages on 2026-10-01. They establish the three firm-level platforms and a model/platform selection flow, but do not publish a model-specific platform mapping for 2-Step Flex.'),
    ('fundingpips','fundingpips-zero','FundingPips Zero platform scope','https://help.fundingpips.com/hc/en-us/articles/43468639481105-Account-Workspace','FundingPips account workspace and platform selection — 2026-10-01',
      'FundingPips lists MetaTrader 5, cTrader, and Match-Trader as firm-level platforms. Its official onboarding describes choosing a model, account size, and platform, but the reviewed public material does not specify the exact platform choices enabled for this offer. Confirm the platform in the live offer selector before purchase.',
      'Reviewed FundingPips official account-workspace and onboarding pages on 2026-10-01. They establish the three firm-level platforms and a model/platform selection flow, but do not publish a model-specific platform mapping for FundingPips Zero.'),
    ('fundingpips','1-step-flex','FundingPips 1-Step Flex platform scope','https://help.fundingpips.com/hc/en-us/articles/43468639481105-Account-Workspace','FundingPips account workspace and platform selection — 2026-10-01',
      'FundingPips lists MetaTrader 5, cTrader, and Match-Trader as firm-level platforms. Its official onboarding describes choosing a model, account size, and platform, but the reviewed public material does not specify the exact platform choices enabled for this offer. Confirm the platform in the live offer selector before purchase.',
      'Reviewed FundingPips official account-workspace and onboarding pages on 2026-10-01. They establish the three firm-level platforms and a model/platform selection flow, but do not publish a model-specific platform mapping for 1 Step Flex.'),
    ('fundingpips','2-step-standard','FundingPips 2-Step Standard platform scope','https://help.fundingpips.com/hc/en-us/articles/43468639481105-Account-Workspace','FundingPips account workspace and platform selection — 2026-10-01',
      'FundingPips lists MetaTrader 5, cTrader, and Match-Trader as firm-level platforms. Its official onboarding describes choosing a model, account size, and platform, but the reviewed public material does not specify the exact platform choices enabled for this offer. Confirm the platform in the live offer selector before purchase.',
      'Reviewed FundingPips official account-workspace and onboarding pages on 2026-10-01. They establish the three firm-level platforms and a model/platform selection flow, but do not publish a model-specific platform mapping for 2-Step Standard.'),
    ('goat-funded-trader','3-step','Goat Funded Trader 3-Step platform scope','https://help.goatfundedtrader.com/en/articles/10741900-which-platforms-can-i-trade-on','Goat Funded Trader platform availability — 2026-10-01',
      'Goat Funded Trader lists cTrader, TradeLocker, MatchTrader, Volumetrica, and MT5 at firm level. The official platform FAQ does not map each platform to this offer. MT5 and cTrader are unavailable to U.S.-located clients; confirm the choices shown for this offer and location in the live selector.',
      'Reviewed Goat Funded Trader official platform FAQ on 2026-10-01. It lists five firm-level platforms and U.S. restrictions for MT5/cTrader, but does not publish the offer-level platform mapping for 3-Step.'),
    ('goat-funded-trader','goat-1-dollar','Goat Funded Trader Goat $1 platform scope','https://help.goatfundedtrader.com/en/articles/10741900-which-platforms-can-i-trade-on','Goat Funded Trader platform availability — 2026-10-01',
      'Goat Funded Trader lists cTrader, TradeLocker, MatchTrader, Volumetrica, and MT5 at firm level. The official platform FAQ does not map each platform to this offer. MT5 and cTrader are unavailable to U.S.-located clients; confirm the choices shown for this offer and location in the live selector.',
      'Reviewed Goat Funded Trader official platform FAQ on 2026-10-01. It lists five firm-level platforms and U.S. restrictions for MT5/cTrader, but does not publish the offer-level platform mapping for Goat $1.'),
    ('goat-funded-trader','pay-later','Goat Funded Trader Pay Later platform scope','https://help.goatfundedtrader.com/en/articles/10741900-which-platforms-can-i-trade-on','Goat Funded Trader platform availability — 2026-10-01',
      'Goat Funded Trader lists cTrader, TradeLocker, MatchTrader, Volumetrica, and MT5 at firm level. The official platform FAQ does not map each platform to this offer. MT5 and cTrader are unavailable to U.S.-located clients; confirm the choices shown for this offer and location in the live selector.',
      'Reviewed Goat Funded Trader official platform FAQ on 2026-10-01. It lists five firm-level platforms and U.S. restrictions for MT5/cTrader, but does not publish the offer-level platform mapping for Pay Later.'),
    ('goat-funded-trader','goat-blitz','Goat Funded Trader Goat Blitz platform scope','https://help.goatfundedtrader.com/en/articles/10741900-which-platforms-can-i-trade-on','Goat Funded Trader platform availability — 2026-10-01',
      'Goat Funded Trader lists cTrader, TradeLocker, MatchTrader, Volumetrica, and MT5 at firm level. The official platform FAQ does not map each platform to this offer. MT5 and cTrader are unavailable to U.S.-located clients; confirm the choices shown for this offer and location in the live selector.',
      'Reviewed Goat Funded Trader official platform FAQ on 2026-10-01. It lists five firm-level platforms and U.S. restrictions for MT5/cTrader, but does not publish the offer-level platform mapping for Goat Blitz.'),
    ('goat-funded-trader','instant-pro','Goat Funded Trader Instant Pro platform scope','https://help.goatfundedtrader.com/en/articles/10741900-which-platforms-can-i-trade-on','Goat Funded Trader platform availability — 2026-10-01',
      'Goat Funded Trader lists cTrader, TradeLocker, MatchTrader, Volumetrica, and MT5 at firm level. The official platform FAQ does not map each platform to this offer. MT5 and cTrader are unavailable to U.S.-located clients; confirm the choices shown for this offer and location in the live selector.',
      'Reviewed Goat Funded Trader official platform FAQ on 2026-10-01. It lists five firm-level platforms and U.S. restrictions for MT5/cTrader, but does not publish the offer-level platform mapping for Instant Pro.')
), updated as (
  update bullish_banana.programs p
  set commercial_details = coalesce(p.commercial_details, '{}'::jsonb) || jsonb_build_object(
    'platform_availability_note', o.disclosure,
    'platform_scope_verified_at', '2026-10-01'
  ), updated_at = now()
  from bullish_banana.firms f, offers o
  where p.firm_id = f.id and f.slug = o.firm_slug and p.slug = o.program_slug
    and p.market_type = 'forex' and p.status in ('published','in_review')
  returning p.id, p.firm_id, p.slug
)
insert into bullish_banana.sources (program_id, source_url, source_label, notes)
select p.id, o.source_url, o.source_title || ' — ' || p.slug, o.disclosure
from updated p
join bullish_banana.firms f on f.id = p.firm_id
join offers o on f.slug = o.firm_slug and p.slug = o.program_slug
where not exists (select 1 from bullish_banana.sources s
  where s.program_id = p.id and s.source_label = o.source_title || ' — ' || p.slug);

with offers(firm_slug, program_slug, source_url, source_title, disclosure, verification) as (
  values
    ('fundingpips','2-step-pro-model','https://help.fundingpips.com/hc/en-us/articles/43468639481105-Account-Workspace','FundingPips account workspace and platform selection — 2026-10-01','FundingPips lists MetaTrader 5, cTrader, and Match-Trader as firm-level platforms. Its official onboarding describes choosing a model, account size, and platform, but the reviewed public material does not specify the exact platform choices enabled for this offer. Confirm the platform in the live offer selector before purchase.','Reviewed official account-workspace and onboarding pages 2026-10-01; they do not publish a model-specific platform mapping for 2-Step Pro.'),
    ('fundingpips','2-step-flex','https://help.fundingpips.com/hc/en-us/articles/43468639481105-Account-Workspace','FundingPips account workspace and platform selection — 2026-10-01','FundingPips lists MetaTrader 5, cTrader, and Match-Trader as firm-level platforms. Its official onboarding describes choosing a model, account size, and platform, but the reviewed public material does not specify the exact platform choices enabled for this offer. Confirm the platform in the live offer selector before purchase.','Reviewed official account-workspace and onboarding pages 2026-10-01; they do not publish a model-specific platform mapping for 2-Step Flex.'),
    ('fundingpips','fundingpips-zero','https://help.fundingpips.com/hc/en-us/articles/43468639481105-Account-Workspace','FundingPips account workspace and platform selection — 2026-10-01','FundingPips lists MetaTrader 5, cTrader, and Match-Trader as firm-level platforms. Its official onboarding describes choosing a model, account size, and platform, but the reviewed public material does not specify the exact platform choices enabled for this offer. Confirm the platform in the live offer selector before purchase.','Reviewed official account-workspace and onboarding pages 2026-10-01; they do not publish a model-specific platform mapping for FundingPips Zero.'),
    ('fundingpips','1-step-flex','https://help.fundingpips.com/hc/en-us/articles/43468639481105-Account-Workspace','FundingPips account workspace and platform selection — 2026-10-01','FundingPips lists MetaTrader 5, cTrader, and Match-Trader as firm-level platforms. Its official onboarding describes choosing a model, account size, and platform, but the reviewed public material does not specify the exact platform choices enabled for this offer. Confirm the platform in the live offer selector before purchase.','Reviewed official account-workspace and onboarding pages 2026-10-01; they do not publish a model-specific platform mapping for 1 Step Flex.'),
    ('fundingpips','2-step-standard','https://help.fundingpips.com/hc/en-us/articles/43468639481105-Account-Workspace','FundingPips account workspace and platform selection — 2026-10-01','FundingPips lists MetaTrader 5, cTrader, and Match-Trader as firm-level platforms. Its official onboarding describes choosing a model, account size, and platform, but the reviewed public material does not specify the exact platform choices enabled for this offer. Confirm the platform in the live offer selector before purchase.','Reviewed official account-workspace and onboarding pages 2026-10-01; they do not publish a model-specific platform mapping for 2-Step Standard.'),
    ('goat-funded-trader','3-step','https://help.goatfundedtrader.com/en/articles/10741900-which-platforms-can-i-trade-on','Goat Funded Trader platform availability — 2026-10-01','Goat Funded Trader lists cTrader, TradeLocker, MatchTrader, Volumetrica, and MT5 at firm level. The official platform FAQ does not map each platform to this offer. MT5 and cTrader are unavailable to U.S.-located clients; confirm the choices shown for this offer and location in the live selector.','Reviewed official platform FAQ 2026-10-01; it lists firm-level platforms and U.S. restrictions but not the offer-level mapping for 3-Step.'),
    ('goat-funded-trader','goat-1-dollar','https://help.goatfundedtrader.com/en/articles/10741900-which-platforms-can-i-trade-on','Goat Funded Trader platform availability — 2026-10-01','Goat Funded Trader lists cTrader, TradeLocker, MatchTrader, Volumetrica, and MT5 at firm level. The official platform FAQ does not map each platform to this offer. MT5 and cTrader are unavailable to U.S.-located clients; confirm the choices shown for this offer and location in the live selector.','Reviewed official platform FAQ 2026-10-01; it lists firm-level platforms and U.S. restrictions but not the offer-level mapping for Goat $1.'),
    ('goat-funded-trader','pay-later','https://help.goatfundedtrader.com/en/articles/10741900-which-platforms-can-i-trade-on','Goat Funded Trader platform availability — 2026-10-01','Goat Funded Trader lists cTrader, TradeLocker, MatchTrader, Volumetrica, and MT5 at firm level. The official platform FAQ does not map each platform to this offer. MT5 and cTrader are unavailable to U.S.-located clients; confirm the choices shown for this offer and location in the live selector.','Reviewed official platform FAQ 2026-10-01; it lists firm-level platforms and U.S. restrictions but not the offer-level mapping for Pay Later.'),
    ('goat-funded-trader','goat-blitz','https://help.goatfundedtrader.com/en/articles/10741900-which-platforms-can-i-trade-on','Goat Funded Trader platform availability — 2026-10-01','Goat Funded Trader lists cTrader, TradeLocker, MatchTrader, Volumetrica, and MT5 at firm level. The official platform FAQ does not map each platform to this offer. MT5 and cTrader are unavailable to U.S.-located clients; confirm the choices shown for this offer and location in the live selector.','Reviewed official platform FAQ 2026-10-01; it lists firm-level platforms and U.S. restrictions but not the offer-level mapping for Goat Blitz.'),
    ('goat-funded-trader','instant-pro','https://help.goatfundedtrader.com/en/articles/10741900-which-platforms-can-i-trade-on','Goat Funded Trader platform availability — 2026-10-01','Goat Funded Trader lists cTrader, TradeLocker, MatchTrader, Volumetrica, and MT5 at firm level. The official platform FAQ does not map each platform to this offer. MT5 and cTrader are unavailable to U.S.-located clients; confirm the choices shown for this offer and location in the live selector.','Reviewed official platform FAQ 2026-10-01; it lists firm-level platforms and U.S. restrictions but not the offer-level mapping for Instant Pro.')
)
insert into bullish_banana.data_verifications (program_id, verified_at, notes)
select p.id, '2026-10-01T04:00:00+09:00'::timestamptz, o.verification
from offers o
join bullish_banana.firms f on f.slug = o.firm_slug
join bullish_banana.programs p on p.firm_id = f.id and p.slug = o.program_slug
where p.market_type = 'forex' and p.status in ('published','in_review')
  and not exists (select 1 from bullish_banana.data_verifications v
    where v.program_id = p.id and v.notes = o.verification);

commit;
