-- Goat Funded Trader current selector offers and first-party help-center models.
-- Captured 2026-09-28. Selector-visible offers are published; help-center-only
-- products stay in review until current checkout availability is reconfirmed.
set search_path = bullish_banana, extensions, public;

insert into bullish_banana.firms (name, slug, description, website_url, status, market_type)
values ('Goat Funded Trader', 'goat-funded-trader', 'A simulated Forex evaluation and instant-funding provider with account-size-specific challenges and reward rules.', 'https://www.goatfundedtrader.com/', 'published', 'forex')
on conflict (slug) do update
set name = excluded.name, description = excluded.description, website_url = excluded.website_url,
    status = case when bullish_banana.firms.status = 'published' then 'published' else excluded.status end,
    updated_at = now();

insert into bullish_banana.firm_markets (firm_id, market_type)
select id, 'forex' from bullish_banana.firms where slug = 'goat-funded-trader'
on conflict (firm_id, market_type) do nothing;

insert into bullish_banana.firm_profiles (firm_id, country_code, legal_entity_name, supported_assets, profile_details)
select id, 'HK', 'Wishes Tower International Limited', array['Forex','Crypto','Indices','Metals','Commodities']::text[],
  '{"established_year":null,"operator_disclosure":"Current site footer identifies Goat Funded Trader as a trade name of Wishes Tower International Limited (Hong Kong, company 76428795) and Goat Funded LTD (Saint Lucia, company 2025-00240) as the provider of the simulated trading services. Preserve both disclosed roles; the public terms and service-provider disclosure should be reconciled before presenting one entity as the sole operator.","service_model":"The current legal disclosure describes demo/simulated accounts and evaluation services.","platforms_note":"The public selector offers platform choices, but model-, size-, and region-specific availability was not reliably mapped. Do not infer platform support.","eligibility_note":"The public footer says MT5 is not intended for U.S. citizens/residents and should not be used where unlawful. Complete restricted-country list not confirmed.","fee_refund_conflict":"The selector labels the fee 100% refundable; Terms contain no-refund wording. Eligibility and conditions need reconciliation before describing a universal refund.","current_product_scope":"Six purchase combinations visible in the current Forex model selector: 1-Step GOAT, 2-Step GOAT, 2-Step Standard, Instant HERO, Instant GOAT, and Instant PREMIUM. Other Help Center model articles are staged for availability review."}'::jsonb
from bullish_banana.firms where slug = 'goat-funded-trader'
on conflict (firm_id) do update
set country_code = excluded.country_code, legal_entity_name = excluded.legal_entity_name,
    supported_assets = excluded.supported_assets,
    profile_details = bullish_banana.firm_profiles.profile_details || excluded.profile_details,
    updated_at = now();

insert into bullish_banana.programs (
  firm_id, name, slug, description, program_type, market_type, status, currency,
  account_sizes, max_leverage, profit_split_percent, payout_frequency,
  minimum_trading_days, news_allowed, weekend_holding_allowed, commercial_details,
  published_at, archived_at
)
select f.id, p.name, p.slug, p.description, p.program_type, 'forex', p.status, 'USD',
       p.account_sizes::jsonb, p.max_leverage, p.profit_split_percent, p.payout_frequency,
       p.minimum_trading_days, null::boolean, null::boolean, p.commercial_details::jsonb,
       case when p.status = 'published' then now() else null end, null
from bullish_banana.firms f
join (values
  ('1-Step GOAT', '1-step-goat', 'Single-phase Forex evaluation with a 10% target and current-purchase 3% daily and 6% static overall limits.', 'evaluation', 'published', '[{"account_size":5000,"currency":"USD"},{"account_size":10000,"currency":"USD"},{"account_size":25000,"currency":"USD"},{"account_size":50000,"currency":"USD"},{"account_size":100000,"currency":"USD"},{"account_size":200000,"currency":"USD"}]', 100::numeric, 80::numeric, 'Every 14 days', 3, '{"account_size_prices":[{"account_size":5000,"fee":41,"list_fee":74,"currency":"USD"},{"account_size":10000,"fee":63,"list_fee":114,"currency":"USD"},{"account_size":25000,"fee":118,"list_fee":214,"currency":"USD"},{"account_size":50000,"fee":173,"list_fee":314,"currency":"USD"},{"account_size":100000,"fee":292,"list_fee":530,"currency":"USD"},{"account_size":200000,"fee":503,"list_fee":914,"currency":"USD"}],"pricing_capture":"Current official model selector, USD prices displayed 2026-09-28. Promotion end date and checkout eligibility were not stated.","payout_rules":"80% base reward share; 100% split is an optional paid add-on. Biweekly cycle. Current-purchase funded payout eligibility requires four qualifying days for accounts purchased from 2026-07-27; older purchases differ. Funded profit cap and initial withdrawal cap apply per official rules.","fee_refund_policy":"Selector calls the one-time fee 100% refundable; Terms include no-refund wording. Conditions not reconciled.","news_weekend_note":"Not stated for this model in the captured sources.","consistency_rule":"No consistency rule on the evaluation or funded model per official article.","purchase_date_variants":"Daily drawdown is 4% for earlier purchases and 3% for purchases from 2026-08-01. Preserve date-scoped rule history.","promotion_note":"Selector displayed sale and crossed-out regular prices. Site separately advertised limited-time and first-purchase codes; code stacking and expiry not verified."}'),
  ('2-Step GOAT', '2-step-goat', 'Two-phase Forex evaluation with 8% and 6% targets, 4% daily drawdown, and 10% static maximum loss.', 'evaluation', 'published', '[{"account_size":5000,"currency":"USD"},{"account_size":10000,"currency":"USD"},{"account_size":25000,"currency":"USD"},{"account_size":50000,"currency":"USD"},{"account_size":100000,"currency":"USD"},{"account_size":150000,"currency":"USD"}]', 100::numeric, 80::numeric, 'Every 14 days', 3, '{"account_size_prices":[{"account_size":5000,"fee":17,"list_fee":36,"currency":"USD"},{"account_size":10000,"fee":36,"list_fee":65,"currency":"USD"},{"account_size":25000,"fee":87,"list_fee":158,"currency":"USD"},{"account_size":50000,"fee":169,"list_fee":308,"currency":"USD"},{"account_size":100000,"fee":263,"list_fee":478,"currency":"USD"},{"account_size":150000,"fee":417,"list_fee":758,"currency":"USD"}],"pricing_capture":"Current official model selector, USD prices displayed 2026-09-28. Promotion end date and checkout eligibility were not stated.","payout_rules":"80% base split with optional paid 100% add-on; biweekly. Four qualifying funded days apply to purchases from 2026-07-25. Official FAQ describes a daily funded profit cap and first-two-payout withdrawal caps.","fee_refund_policy":"Selector calls the one-time fee 100% refundable; Terms include no-refund wording. Conditions not reconciled.","news_weekend_note":"Not stated in the captured model sources.","consistency_rule":"No consistency rule stated for evaluation or funded phases.","promotion_note":"Selector displayed sale and crossed-out regular prices. Site separately advertised limited-time and first-purchase codes; code stacking and expiry not verified."}'),
  ('2-Step Standard', '2-step-standard', 'Two-phase Forex evaluation with 10% and 5% targets, 5% daily drawdown, and 10% static maximum loss.', 'evaluation', 'published', '[{"account_size":5000,"currency":"USD"},{"account_size":10000,"currency":"USD"},{"account_size":25000,"currency":"USD"},{"account_size":50000,"currency":"USD"},{"account_size":100000,"currency":"USD"},{"account_size":200000,"currency":"USD"}]', 100::numeric, 80::numeric, 'Every 14 days', 3, '{"account_size_prices":[{"account_size":5000,"fee":17,"list_fee":52,"currency":"USD"},{"account_size":10000,"fee":50,"list_fee":90,"currency":"USD"},{"account_size":25000,"fee":129,"list_fee":234,"currency":"USD"},{"account_size":50000,"fee":197,"list_fee":358,"currency":"USD"},{"account_size":100000,"fee":345,"list_fee":628,"currency":"USD"},{"account_size":200000,"fee":659,"list_fee":1198,"currency":"USD"}],"pricing_capture":"Current official model selector, USD prices displayed 2026-09-28. Promotion end date and checkout eligibility were not stated.","payout_rules":"80% base split, optional paid 100% add-on, and biweekly reward cycle. Official rules describe first-two-payout withdrawal caps.","fee_refund_policy":"Selector calls the one-time fee 100% refundable; Terms include no-refund wording. Conditions not reconciled.","news_weekend_note":"Not stated in the captured model sources.","consistency_rule":"No consistency rule stated for evaluation or funded phases.","promotion_note":"Selector displayed sale and crossed-out regular prices. Site separately advertised limited-time and first-purchase codes; code stacking and expiry not verified."}'),
  ('3-Step', '3-step', 'Three-phase Forex evaluation listed in the official Help Center; current purchase availability and price schedule need confirmation.', 'evaluation', 'in_review', '[]', null::numeric, 80::numeric, 'Every 14 days', null::integer, '{"availability_note":"Help Center model index includes 3-Step, but the current public purchase selector did not expose it during review.","fee_refund_policy":"Selector-level price and refund conditions unavailable; Terms include no-refund wording.","payout_rules":"Official Help Center states 80% base share and biweekly rewards with purchase-date payout day and withdrawal-cap rules.","promotion_note":"Current price and account sizes not stated in the selector review."}'),
  ('2-Step PRO', '2-step-pro', 'Two-phase Forex evaluation listed in the official Help Center; current purchase availability and price schedule need confirmation.', 'evaluation', 'in_review', '[]', null::numeric, 80::numeric, 'Every 14 days', 3, '{"availability_note":"Help Center model index includes 2-Step PRO, but the current public purchase selector did not expose it during review.","fee_refund_policy":"Selector-level price and refund conditions unavailable; Terms include no-refund wording.","payout_rules":"Official Help Center states 80% base share and biweekly rewards with initial withdrawal limits.","promotion_note":"Current price and account sizes not stated in the selector review."}'),
  ('Instant HERO', 'instant-hero', 'Immediate Forex funding with a 3% trailing daily limit, 5% trailing maximum loss, and HERO-specific floating-loss and payout rules.', 'instant_funding', 'published', '[{"account_size":5000,"currency":"USD"},{"account_size":10000,"currency":"USD"},{"account_size":15000,"currency":"USD"},{"account_size":25000,"currency":"USD"},{"account_size":50000,"currency":"USD"},{"account_size":100000,"currency":"USD"},{"account_size":200000,"currency":"USD"},{"account_size":300000,"currency":"USD"},{"account_size":400000,"currency":"USD"}]', 100::numeric, 90::numeric, 'Every 14 days', null::integer, '{"account_size_prices":[{"account_size":5000,"fee":17,"list_fee":58,"currency":"USD"},{"account_size":10000,"fee":59,"list_fee":107,"currency":"USD"},{"account_size":15000,"fee":86,"list_fee":157,"currency":"USD"},{"account_size":25000,"fee":132,"list_fee":240,"currency":"USD"},{"account_size":50000,"fee":196,"list_fee":357,"currency":"USD"},{"account_size":100000,"fee":361,"list_fee":657,"currency":"USD"},{"account_size":200000,"fee":636,"list_fee":1157,"currency":"USD"},{"account_size":300000,"fee":915,"list_fee":1663,"currency":"USD"},{"account_size":400000,"fee":1282,"list_fee":2330,"currency":"USD"}],"pricing_capture":"Current official model selector, USD prices displayed 2026-09-28. Promotion end date and checkout eligibility were not stated.","funded_rules":"Six qualifying days at 0.5% each per official Help Center; 1% floating-loss breach; 15% funded consistency rule; 90% base split and optional paid 100% add-on.","fee_refund_policy":"Selector calls the one-time fee 100% refundable; Terms include no-refund wording. Conditions not reconciled.","promotion_note":"Selector displayed sale and crossed-out regular prices. Site separately advertised limited-time and first-purchase codes; code stacking and expiry not verified."}'),
  ('Instant GOAT', 'instant-goat', 'Immediate Forex funding with 3% trailing daily and 6% trailing maximum loss limits, plus floating-loss and consistency rules.', 'instant_funding', 'published', '[{"account_size":5000,"currency":"USD"},{"account_size":10000,"currency":"USD"},{"account_size":25000,"currency":"USD"},{"account_size":50000,"currency":"USD"},{"account_size":100000,"currency":"USD"},{"account_size":200000,"currency":"USD"},{"account_size":300000,"currency":"USD"},{"account_size":400000,"currency":"USD"}]', 100::numeric, 80::numeric, 'Every 14 days', null::integer, '{"account_size_prices":[{"account_size":5000,"fee":59,"list_fee":108,"currency":"USD"},{"account_size":10000,"fee":87,"list_fee":158,"currency":"USD"},{"account_size":25000,"fee":175,"list_fee":318,"currency":"USD"},{"account_size":50000,"fee":268,"list_fee":488,"currency":"USD"},{"account_size":100000,"fee":448,"list_fee":815,"currency":"USD"},{"account_size":200000,"fee":915,"list_fee":1663,"currency":"USD"},{"account_size":300000,"fee":1319,"list_fee":2398,"currency":"USD"},{"account_size":400000,"fee":1649,"list_fee":2998,"currency":"USD"}],"pricing_capture":"Current official model selector, USD prices displayed 2026-09-28. Promotion end date and checkout eligibility were not stated.","funded_rules":"Five qualifying days at 0.5% each; 2% floating-loss breach; 15% funded consistency; max loss resets after payout; 80% base share and optional paid 100% add-on.","fee_refund_policy":"Selector calls the one-time fee 100% refundable; Terms include no-refund wording. Conditions not reconciled.","promotion_note":"Selector displayed sale and crossed-out regular prices. Site separately advertised limited-time and first-purchase codes; code stacking and expiry not verified."}'),
  ('Instant PREMIUM', 'instant-premium', 'Immediate Forex funding with no consistency rule and purchase-date-specific loss and reward terms.', 'instant_funding', 'published', '[{"account_size":5000,"currency":"USD"},{"account_size":10000,"currency":"USD"},{"account_size":15000,"currency":"USD"},{"account_size":25000,"currency":"USD"},{"account_size":50000,"currency":"USD"},{"account_size":100000,"currency":"USD"},{"account_size":150000,"currency":"USD"}]', 50::numeric, 80::numeric, 'Every 14 days', null::integer, '{"account_size_prices":[{"account_size":5000,"fee":87,"list_fee":158,"currency":"USD"},{"account_size":10000,"fee":163,"list_fee":297,"currency":"USD"},{"account_size":15000,"fee":218,"list_fee":397,"currency":"USD"},{"account_size":25000,"fee":310,"list_fee":563,"currency":"USD"},{"account_size":50000,"fee":447,"list_fee":813,"currency":"USD"},{"account_size":100000,"fee":722,"list_fee":1313,"currency":"USD"},{"account_size":150000,"fee":1172,"list_fee":2130,"currency":"USD"}],"pricing_capture":"Current official model selector, USD prices displayed 2026-09-28. Promotion end date and checkout eligibility were not stated.","funded_rules":"3% daily drawdown, 6% intraday trailing maximum loss, no consistency rule, five qualifying days at 0.5%, 80% split, 1:50 leverage. Current FAQ says a 1% floating-loss breach and 14-day cycle for purchases from 2026-09-21; older purchases differ.","fee_refund_policy":"Selector calls the one-time fee 100% refundable; Terms include no-refund wording. Conditions not reconciled.","purchase_date_variants":"Floating-loss threshold changed from 1.5% to 1% for purchases from 2026-09-02. Reward cycle changed from every 10 days to biweekly for purchases from 2026-09-21.","promotion_note":"Selector displayed sale and crossed-out regular prices. Site separately advertised limited-time and first-purchase codes; code stacking and expiry not verified."}'),
  ('Instant PRO', 'instant-pro', 'Immediate funding model listed in the official Help Center; current purchase availability and price schedule need confirmation.', 'instant_funding', 'in_review', '[]', null::numeric, 80::numeric, 'Every 14 days', 5, '{"availability_note":"Help Center model index includes Instant PRO, but the current public selector did not expose it during review.","funded_rules":"No daily drawdown; 4% trailing maximum loss resetting after payout; 2% floating-loss breach; 20% funded consistency; five qualifying days; 80% base split and optional paid 100% add-on.","promotion_note":"Current price, account sizes, and selector availability not confirmed."}'),
  ('GOAT Blitz', 'goat-blitz', 'Limited-availability Forex evaluation documented in the official Help Center; current selector status and purchase schedule need confirmation.', 'evaluation', 'in_review', '[]', null::numeric, 80::numeric, 'Every 14 days', 5, '{"availability_note":"Official article says GOAT Blitz appears randomly on two weekends per month for a limited time. Current selector only exposed a hidden special-promo entry, so availability and price require checkout confirmation.","funded_rules":"15% consistency applies to the funded stage; five trading days per payout; 2% floating-loss rule.","promotion_note":"No size/fee schedule captured."}'),
  ('Pay Later', 'pay-later', 'One-phase evaluation with a small initial payment and a separate activation payment due after passing; current checkout availability needs confirmation.', 'evaluation', 'in_review', '[]', null::numeric, 80::numeric, 'Every 14 days', null::integer, '{"availability_note":"Help Center model index includes Pay Later but it did not appear in the current public selector.","pricing_note":"Official Help Center describes a $5 initial payment and a separate activation balance due after passing; exact account-size-specific total fees were not captured.","activation_fee":"Activation balance must be paid within 30 days of the activation link; evaluation profits cannot be used to pay it.","funded_rules":"Official article describes 4% phase target, trailing maximum drawdown and funded-phase daily loss; exact size-specific terms and checkout availability require review.","promotion_note":"No complete fee schedule captured."}'),
  ('Goat $1', 'goat-1-dollar', 'Single-size $1,000 instant account documented in the Help Center; current public checkout availability needs confirmation.', 'instant_funding', 'in_review', '[{"account_size":1000,"currency":"USD"}]', null::numeric, 80::numeric, 'Every 14 days', null::integer, '{"availability_note":"Help Center article lists a $1,000, $1 instant offer; current public selector did not expose it.","funded_rules":"28-day expiry, $100 minimum withdrawal and $100 lifetime withdrawal cap, one-account-per-user, 3% static daily drawdown, 6% trailing maximum loss, 2% floating-loss rule, 15% consistency, and three qualifying days per payout.","promotion_note":"One-time price stated as $1 in current Help Center article; confirm live purchase availability."}')
) as p(name, slug, description, program_type, status, account_sizes, max_leverage, profit_split_percent, payout_frequency, minimum_trading_days, commercial_details)
  on true
where f.slug = 'goat-funded-trader'
on conflict (firm_id, slug) do update
set name = excluded.name, description = excluded.description, program_type = excluded.program_type,
    market_type = excluded.market_type, status = excluded.status, currency = excluded.currency,
    account_sizes = excluded.account_sizes, max_leverage = excluded.max_leverage,
    profit_split_percent = excluded.profit_split_percent, payout_frequency = excluded.payout_frequency,
    minimum_trading_days = excluded.minimum_trading_days,
    commercial_details = excluded.commercial_details,
    published_at = excluded.published_at, archived_at = null, updated_at = now();

insert into bullish_banana.program_phases (
  program_id, phase_number, name, profit_target_percent, daily_drawdown_percent,
  maximum_drawdown_percent, drawdown_type, minimum_trading_days, raw_rules
)
select p.id, x.phase_number, x.name, x.target, x.daily_loss, x.maximum_loss,
       x.drawdown_type, x.days, x.rules::jsonb
from bullish_banana.programs p
join bullish_banana.firms f on f.id = p.firm_id
join (values
  ('1-step-goat', 1, 'Evaluation', 10::numeric, 3::numeric, 6::numeric, 'static', 3, '{"time_limit":"unlimited","purchase_date_variant":"Daily loss is 4% for purchases before 2026-08-01; 3% from 2026-08-01 onward.","source_note":"Official 1-Step GOAT article and live selector, captured 2026-09-28."}'),
  ('2-step-goat', 1, 'Evaluation Phase 1', 8::numeric, 4::numeric, 10::numeric, 'static', 3, '{"time_limit":"unlimited","source_note":"Official 2-Step GOAT article, captured 2026-09-28."}'),
  ('2-step-goat', 2, 'Evaluation Phase 2', 6::numeric, 4::numeric, 10::numeric, 'static', 3, '{"time_limit":"unlimited","source_note":"Official 2-Step GOAT article, captured 2026-09-28."}'),
  ('2-step-standard', 1, 'Evaluation Phase 1', 10::numeric, 5::numeric, 10::numeric, 'static', 3, '{"time_limit":"unlimited","consistency_rule":"none","source_note":"Official 2-Step Standard article and live selector, captured 2026-09-28."}'),
  ('2-step-standard', 2, 'Evaluation Phase 2', 5::numeric, 5::numeric, 10::numeric, 'static', 3, '{"time_limit":"unlimited","consistency_rule":"none","source_note":"Official 2-Step Standard article and live selector, captured 2026-09-28."}'),
  ('3-step', 1, 'Evaluation Phase 1', 6::numeric, 4::numeric, 8::numeric, 'static', null::integer, '{"time_limit":"unlimited","availability_note":"Help Center model not present in live public selector; review status retained."}'),
  ('3-step', 2, 'Evaluation Phase 2', 6::numeric, 4::numeric, 8::numeric, 'static', null::integer, '{"time_limit":"unlimited","availability_note":"Help Center model not present in live public selector; review status retained."}'),
  ('3-step', 3, 'Evaluation Phase 3', 6::numeric, 4::numeric, 8::numeric, 'static', null::integer, '{"time_limit":"unlimited","availability_note":"Help Center model not present in live public selector; review status retained."}'),
  ('2-step-pro', 1, 'Evaluation Phase 1', 8::numeric, 4::numeric, 8::numeric, 'static', 3, '{"time_limit":"unlimited","availability_note":"Help Center model not present in live public selector; review status retained."}'),
  ('2-step-pro', 2, 'Evaluation Phase 2', 4::numeric, 4::numeric, 8::numeric, 'static', 3, '{"time_limit":"unlimited","availability_note":"Help Center model not present in live public selector; review status retained."}'),
  ('instant-hero', 1, 'Funded account rules', null::numeric, 3::numeric, 5::numeric, 'trailing', 6, '{"evaluation":"none; immediate funded access","daily_drawdown":"3% trailing","maximum_loss":"5% trailing; resets after payout","floating_loss_breach_percent":1,"consistency_rule":"15% funded","payout_days":"six qualifying days, each with at least 0.5% profit","source_note":"Official Instant HERO article, captured 2026-09-28."}'),
  ('instant-goat', 1, 'Funded account rules', null::numeric, 3::numeric, 6::numeric, 'trailing', 5, '{"evaluation":"none; immediate funded access","daily_drawdown":"3% trailing","maximum_loss":"6% trailing; resets after payout","floating_loss_breach_percent":2,"consistency_rule":"15% funded","payout_days":"five qualifying days, each with at least 0.5% profit","source_note":"Official Instant GOAT article, captured 2026-09-28."}'),
  ('instant-premium', 1, 'Funded account rules', null::numeric, 3::numeric, 6::numeric, 'intraday trailing', 5, '{"evaluation":"none; immediate funded access","daily_drawdown":"3%","maximum_loss":"6% intraday trailing; resets after payout","floating_loss_breach_percent":1,"consistency_rule":"none","payout_days":"five qualifying days, each with at least 0.5% profit","purchase_date_variant":"Floating-loss limit changed from 1.5% to 1% on 2026-09-02; payout cycle changed from 10 to 14 days on 2026-09-21.","source_note":"Official Instant Premium article, captured 2026-09-28."}'),
  ('instant-pro', 1, 'Funded account rules', null::numeric, null::numeric, 4::numeric, 'trailing', 5, '{"evaluation":"none; immediate funded access","maximum_loss":"4% trailing; resets after payout","floating_loss_breach_percent":2,"consistency_rule":"20% funded","payout_days":"five qualifying days","availability_note":"Help Center model not present in live public selector; review status retained."}'),
  ('goat-blitz', 1, 'Evaluation', 3::numeric, 3::numeric, 5::numeric, 'static daily; trailing maximum', 5, '{"time_limit":"unlimited","maximum_loss_per_trade_percent":2,"availability":"Official article describes intermittent weekend availability; live checkout not confirmed."}'),
  ('goat-blitz', 2, 'Funded account rules', null::numeric, 3::numeric, 5::numeric, 'static daily; trailing maximum', 5, '{"consistency_rule":"15% funded","maximum_loss_per_trade_percent":2,"payout_frequency":"Every 14 days","availability":"Official article describes intermittent weekend availability; live checkout not confirmed."}'),
  ('pay-later', 1, 'Evaluation', 4::numeric, null::numeric, 8::numeric, 'trailing', null::integer, '{"initial_payment_usd":5,"remaining_activation_fee_due_after_passing":true,"activation_window_days":30,"time_limit":"Not stated","availability_note":"Help Center-only; confirm current selector availability and size-specific fee."}'),
  ('pay-later', 2, 'Funded account rules', null::numeric, 3::numeric, 6::numeric, 'trailing', null::integer, '{"payout_frequency":"Every 14 days","availability_note":"Funded stage terms summarized from official Help Center; exact checkout variant remains unconfirmed."}'),
  ('goat-1-dollar', 1, 'Funded account rules', null::numeric, 3::numeric, 6::numeric, 'static daily; trailing maximum', 3, '{"evaluation":"instant funding","maximum_loss_per_trade_percent":2,"consistency_rule":"15%","account_expiry_days":28,"minimum_withdrawal_usd":100,"lifetime_withdrawal_cap_usd":100,"purchase_limit_per_user":1,"availability_note":"Help Center-only; verify current selector availability."}')
) as x(program_slug, phase_number, name, target, daily_loss, maximum_loss, drawdown_type, days, rules)
  on x.program_slug = p.slug
where f.slug = 'goat-funded-trader'
on conflict (program_id, phase_number) do update
set name = excluded.name, profit_target_percent = excluded.profit_target_percent,
    daily_drawdown_percent = excluded.daily_drawdown_percent,
    maximum_drawdown_percent = excluded.maximum_drawdown_percent,
    drawdown_type = excluded.drawdown_type, minimum_trading_days = excluded.minimum_trading_days,
    raw_rules = excluded.raw_rules, updated_at = now();

insert into bullish_banana.sources (firm_id, source_url, source_label, notes)
select f.id, x.url, x.label, x.notes
from bullish_banana.firms f
join (values
  ('https://www.goatfundedtrader.com/model', 'Goat Funded Trader live Forex model selector', 'Current offer combinations, selector-visible account sizes, USD current/list price pairs, leverage, split, and public legal disclosure. Browser-selected each listed account size on 2026-09-28; promo code terms and expiry not confirmed.'),
  ('https://www.goatfundedtrader.com/legal/terms-and-conditions', 'Goat Funded Trader Terms and Conditions', 'Terms include service, prohibited-practice, jurisdiction and no-refund language; compare against selector refundable-fee claim.'),
  ('https://help.goatfundedtrader.com/en/collections/11811982-models', 'Goat Funded Trader Help Center model index', 'First-party model inventory includes additional models not shown in the current public selector; those records remain in review pending checkout proof.')
) as x(url, label, notes) on true
where f.slug = 'goat-funded-trader'
  and not exists (select 1 from bullish_banana.sources s where s.firm_id = f.id and s.source_url = x.url);

insert into bullish_banana.sources (program_id, source_url, source_label, notes)
select p.id, x.url, x.label, x.notes
from bullish_banana.programs p
join bullish_banana.firms f on f.id = p.firm_id
join (values
  ('1-step-goat', 'https://www.goatfundedtrader.com/model', 'Live 1-Step GOAT selector and USD prices', 'Current selector-size choices and price/list-price pairs captured on 2026-09-28; apply promotion/checkout caveats recorded on the program.'),
  ('2-step-goat', 'https://www.goatfundedtrader.com/model', 'Live 2-Step GOAT selector and USD prices', 'Current selector-size choices and price/list-price pairs captured on 2026-09-28; apply promotion/checkout caveats recorded on the program.'),
  ('2-step-standard', 'https://www.goatfundedtrader.com/model', 'Live 2-Step Standard selector and USD prices', 'Current selector-size choices and price/list-price pairs captured on 2026-09-28; apply promotion/checkout caveats recorded on the program.'),
  ('instant-hero', 'https://www.goatfundedtrader.com/model', 'Live Instant HERO selector and USD prices', 'Current selector-size choices and price/list-price pairs captured on 2026-09-28; apply promotion/checkout caveats recorded on the program.'),
  ('instant-goat', 'https://www.goatfundedtrader.com/model', 'Live Instant GOAT selector and USD prices', 'Current selector-size choices and price/list-price pairs captured on 2026-09-28; apply promotion/checkout caveats recorded on the program.'),
  ('instant-premium', 'https://www.goatfundedtrader.com/model', 'Live Instant PREMIUM selector and USD prices', 'Current selector-size choices and price/list-price pairs captured on 2026-09-28; apply promotion/checkout caveats recorded on the program.'),
  ('1-step-goat', 'https://help.goatfundedtrader.com/en/articles/10630134-1-step-model', '1-Step GOAT rules', '10% target, current/legacy daily-loss purchase-date variants, 6% static maximum loss, trading-day and funded reward conditions.'),
  ('2-step-goat', 'https://help.goatfundedtrader.com/en/articles/13575348-2-step-goat-model', '2-Step GOAT rules', 'Phase targets, 4% daily and 10% static loss, minimum days, payout cadence and purchase-date funded reward variants.'),
  ('2-step-standard', 'https://help.goatfundedtrader.com/en/articles/13575169-2-step-standard', '2-Step Standard rules', '10%/5% objectives, 5% daily, 10% static maximum loss, no consistency rule, payout timing.'),
  ('instant-hero', 'https://help.goatfundedtrader.com/en/articles/16097387-instant-hero-model', 'Instant HERO rules', 'Immediate funded account, daily/maximum trailing limits, 1% floating loss, consistency, payout days and share.'),
  ('instant-goat', 'https://help.goatfundedtrader.com/en/articles/13574117-instant-funding-goat-model', 'Instant GOAT rules', 'Immediate funded account, daily/maximum trailing limits, floating loss, consistency and payout days.'),
  ('instant-premium', 'https://help.goatfundedtrader.com/en/articles/16013484-instant-premium-model', 'Instant PREMIUM rules', 'Immediate funded account, daily and trailing max loss, purchase-date floating-loss/reward-cycle variants and no consistency rule.'),
  ('3-step', 'https://help.goatfundedtrader.com/en/articles/10630343-3-step-model', '3-Step rules (availability review)', 'Official Help Center model article exists, but current purchase selector did not expose the offer or fees.'),
  ('2-step-pro', 'https://help.goatfundedtrader.com/en/articles/13778401-2-step-pro-model', '2-Step PRO rules (availability review)', 'Official Help Center model article exists, but current purchase selector did not expose the offer or fees.'),
  ('instant-pro', 'https://help.goatfundedtrader.com/en/articles/13574328-instant-funding-pro-model', 'Instant PRO rules (availability review)', 'Official Help Center model article exists, but current purchase selector did not expose the offer or fees.'),
  ('goat-blitz', 'https://help.goatfundedtrader.com/en/articles/11111955-goat-blitz-model', 'GOAT Blitz rules (availability review)', 'Article says limited weekend availability; checkout price and current offer availability not confirmed.'),
  ('pay-later', 'https://help.goatfundedtrader.com/en/articles/12822025-pay-later-model', 'Pay Later rules (availability review)', 'Article says $5 due initially with a separately payable activation balance; exact current size and total-fee schedule not confirmed.'),
  ('goat-1-dollar', 'https://help.goatfundedtrader.com/en/articles/11769239-goat-1-model', 'Goat $1 rules (availability review)', 'Article states $1,000 instant account, $1 fee and strict expiration/withdrawal caps; current selector availability not confirmed.')
) as x(program_slug, url, label, notes) on x.program_slug = p.slug
where f.slug = 'goat-funded-trader'
  and not exists (select 1 from bullish_banana.sources s where s.program_id = p.id and s.source_url = x.url);

insert into bullish_banana.affiliate_destinations (firm_id, program_id, kind, label, destination_url, is_primary, status)
select f.id, p.id, 'official_site', 'View ' || p.name || ' at Goat Funded Trader', 'https://www.goatfundedtrader.com/model', true, 'active'
from bullish_banana.firms f
join bullish_banana.programs p on p.firm_id = f.id
where f.slug = 'goat-funded-trader'
  and not exists (select 1 from bullish_banana.affiliate_destinations d where d.program_id = p.id and d.kind = 'official_site');

insert into bullish_banana.data_verifications (firm_id, verified_at, notes)
select id, now(), 'Current Forex selector, live model combinations, legal/footer entity disclosures and Help Center model index reviewed against first-party sources on 2026-09-28. Firm is published; legal-entity roles, platform/country details and refund wording remain explicitly noted.'
from bullish_banana.firms f
where slug = 'goat-funded-trader'
  and not exists (select 1 from bullish_banana.data_verifications v where v.firm_id = f.id);

insert into bullish_banana.data_verifications (program_id, verified_at, notes)
select p.id, now(), case when p.status = 'published'
  then 'Current model selector and official model-specific rules reviewed on 2026-09-28. USD current/list price schedule captured for every selectable size. Promo checkout conditions and fee-refund conflict remain disclosed.'
  else 'Official Help Center article reviewed on 2026-09-28, but the current selector did not expose this model. Record remains in review pending live checkout, sizes, and fees.' end
from bullish_banana.programs p
join bullish_banana.firms f on f.id = p.firm_id
where f.slug = 'goat-funded-trader'
  and not exists (select 1 from bullish_banana.data_verifications v where v.program_id = p.id);
